mysql:
  addr: 127.0.0.1
  username: root
  password: root
  port: 3306
  database: test

# redis:
#   addr: 127.0.0.1
#   port: 6379
#   password: root
#   db: 0

server:
  addr: 0.0.0.0
  port: 80

# https://market.aliyun.com/products/57002003/cmapi021970.html
ipinfo:
  authorization: ""

authorize: ""
